server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD} 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update 

# ddl-auto: create 
      # to create new schemas and tables, but it will wipe every data and start fresh
# ddl-auto: update
      # to add data to the existing tables, this will not remove the existing 
      # tables data but will update it with new ones
